### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jnthn18/project9#1]
Looking good, apart from *one* thing. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have *every* file use two-space soft-tabs. (I see some hard-tabs in [here](https://github.com/jnthn18/project9/blob/master/app/helpers/static_helper.rb) and [here](https://github.com/jnthn18/project9/blob/master/app/assets/stylesheets/static.scss), for example.)

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by jnthn18** [comment]
In Sublime it shows as being a two-space soft tab

**Comment by chrisvfritz** [comment]
Reconfiguring your text editor, which it sounds like you've done, will help prevent bad indentation in *future* files, but those videos I linked to along with the `"draw_white_space": "all"` setting in Sublime should help you identify and fix the indentation issues. Let me know if that doesn't work.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by jnthn18** [comment]
Ok it should be all good now, sorry about the wait!

**Comment by chrisvfritz** [comment]
:+1: Looks great!
